tinyMCE.addI18n('nb.phpimage_dlg',{
    tab_general:"Generelt",
    tab_appearance:"Utseende",
    tab_advanced:"Avansert",
    browse:"Browse",
    upload:"Last opp",
    general:"Generelt",
    title:"Tittel",
    preview:"Forhåndsvisning",
    constrain_proportions:"Begrens proporsjonene",
    langdir:"Språkretning",
    langcode:"Språkkode",
    long_desc:"Lenke til lang beskrivelse",
    style:"Stil",
    classes:"Klasser",
    ltr:"Venstre mot høyre",
    rtl:"Høyre mot venstre",
    id:"ID",
    map:"Bildekart",
    swap_image:"Bytt bilde",
    alt_image:"Alternativt bilde",
    mouseover:"ved «mouse over»",
    mouseout:"ved «mouse out»",
    misc:"Diverse",
    example_img:"Forhåndsvisningsbilde",
    missing_alt:"Er du sikker på at du ønsker å fortsette uten en bildebeskrivelse? Uten dette kan bildet bli utilgjengelig for folk med funksjonsnedsettelser, eller for de som bruker en tekst-browser, eller som har slått av visning av bilder.",
    dialog_title:"Legg inn/endre bilde",
    src:"Bilde-URL",
    alt:"Beskrivelse av bilde",
    list:"Bildeliste",
    border:"Kant",
    dimensions:"Dimensjoner",
    vspace:"Vertikal plass",
    hspace:"Horistontal plass",
    align:"Justering",
    align_baseline:"Grunnlinje",
    align_top:"Topp",
    align_middle:"Midt",
    align_bottom:"Bunn",
    align_texttop:"Tekst-topp",
    align_textbottom:"Tekst-bunn",
    align_left:"Venstre",
    align_right:"Høyre",
    image_list:"Bildeliste",
    image_desc:"Legg inn/endre bilde"
});
