tinyMCE.addI18n('nn.phpimage_dlg',{
tab_general:"nnGeneral",
tab_appearance:"nnAppearance",
tab_advanced:"nnAdvanced",
browse:"nnBrowse",
upload:"nnUpload",
general:"nnGeneral",
title:"nTitle",
preview:"nnPreview",
constrain_proportions:"nnConstrain proportions",
langdir:"nLanguage direction",
langcode:"nnLanguage code",
long_desc:"nnLong description link",
style:"nnStyle",
classes:"nnClasses",
ltr:"nnLeft to right",
rtl:"nnRight to left",
id:"nnId",
map:"nnImage map",
swap_image:"nSwap image",
alt_image:"nnAlternative image",
mouseover:"nnfor mouse over",
mouseout:"nnfor mouse out",
misc:"nnMiscellaneous",
example_img:"Appearance preview image",
missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
dialog_title:"Insert/edit image",
src:"Image URL",
alt:"Image description",
list:"Image list",
border:"Border",
dimensions:"Dimensions",
vspace:"Vertical space",
hspace:"Horizontal space",
align:"Alignment",
align_baseline:"nnBaseline",
align_top:"Top",
align_middle:"Middle",
align_bottom:"Bottom",
align_texttop:"Text top",
align_textbottom:"Text bottom",
align_left:"Left",
align_right:"Right",
image_list:"Image list",
image_desc:"Insert/Edit image"
});